import { test } from "node:test";
import assert = require("node:assert/strict");
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import * as coreKernel from "../../src/core-kernel/index";
import type {
  CoreModuleRegistrationEntryId,
  CoreSelectorId,
  CoreSelectorRequest,
  CoreSelectorResult,
  KernelCapability,
  KernelGatewayResult,
  KernelModuleGatewayCreationResult,
  KernelModuleIdentity,
  KernelModuleOrigin,
  KernelModuleRuntime,
  KernelIntegratedCatalog,
  KernelIssue,
  KernelReport,
  KernelRegistryAccessFailure,
  KernelRegistryApiVersion,
  KernelRegistryCreationResult,
  KernelRegistryStartupFailure,
  KernelStartupManifestVersion,
  KernelStartupModuleDeclaration,
  KernelStartupModuleManifest,
  KernelTrustLevel,
  RegistryContributionSummary,
  RegistryModuleSummary,
  RegistrySummary,
  MigrationReport,
  MigrationResult,
  ExtensionRuntimeRequirementV1,
  ModuleIssueCode,
  ModuleKernelIssue,
} from "../../src/core-kernel/index";

type PublicRegistryTypeBoundary = readonly [
  CoreModuleRegistrationEntryId,
  CoreSelectorId,
  CoreSelectorRequest,
  CoreSelectorResult,
  KernelCapability,
  KernelGatewayResult<unknown>,
  KernelModuleGatewayCreationResult,
  KernelModuleIdentity,
  KernelModuleOrigin,
  KernelModuleRuntime,
  KernelRegistryAccessFailure,
  KernelRegistryApiVersion,
  KernelRegistryCreationResult,
  KernelRegistryStartupFailure,
  KernelStartupManifestVersion,
  KernelStartupModuleDeclaration,
  KernelStartupModuleManifest,
  KernelTrustLevel,
  RegistryContributionSummary,
  RegistryModuleSummary,
  RegistrySummary,
  KernelIssue,
  KernelReport,
  MigrationReport,
  MigrationResult,
  ExtensionRuntimeRequirementV1,
  KernelIntegratedCatalog,
  ModuleIssueCode,
  ModuleKernelIssue,
];

test("Core exports only formal production APIs and no retired test vocabulary", () => {
  assert.deepEqual(Object.keys(coreKernel).sort(), [
    "CORE_KERNEL_STARTUP_MANIFEST",
    "CommandBus",
    "K1_SCORE_FEATURE_PROFILE",
    "KernelModuleGateway",
    "KernelRegistry",
    "PURE_CORE_KERNEL_V1_SCOPE",
    "SCORE_DOCUMENT_SCHEMA_VERSION",
    "addFractions",
    "compareFractions",
    "createDiagnostic",
    "createFraction",
    "createKernelRegistry",
    "createKernelValidationReport",
    "createModuleInternalIssue",
    "createScoreDocument",
    "decodeScoreDocument",
    "deriveSequenceEventStarts",
    "encodeScoreDocumentJson",
    "getEffectiveMeasureDuration",
    "getNoteValueDuration",
    "isCanonicalFraction",
    "isJsonValue",
    "isNoteValueBase",
    "isNoteValueDots",
    "isScoreDocumentSchemaVersion",
    "isTransposition",
    "isWrittenPitch",
    "mapCheckpointFailureToKernelIssues",
    "mapCommandBusCreationFailureToKernelIssues",
    "mapCommandFailureToKernelIssues",
    "mapDiagnosticToKernelIssue",
    "mapEventSubscriptionFailureToKernelIssues",
    "mapReadFailureToKernelIssues",
    "mapRegistryAccessFailureToKernelIssues",
    "mapRegistryStartupFailureToKernelIssues",
    "migrateScoreDocument",
    "multiplyFractions",
    "parseScoreDocumentJson",
    "replayCoreCommands",
    "selectDirtyState",
    "selectHistoryState",
    "selectScoreEntity",
    "selectScoreEntityOwnership",
    "selectScoreMetadata",
    "selectScoreRange",
    "subtractFractions",
    "transposeWrittenPitch",
    "validateScoreDocumentSemantics",
    "validateScoreFeatureProfile",
  ]);

  const forbidden = [
    "TICKS_PER_QUARTER",
    "DURATION_TICKS",
    "createK1StandardRiffDocument",
    "createK1TestTechniqueRegistry",
    "CORE_COMMAND_DEFINITIONS",
    "CoreMutation",
    "HistoryEntry",
    "CommittedOperation",
    "deepFreezeValue",
    "EntityIndex",
    "publish",
    "KernelEventBus",
    "cleanStateIdentity",
    "stateIdentityByDocumentVersion",
    "getDocument",
    "setDocument",
    "replaceDocument",
    "registerCoreCommand",
    "unregisterCoreCommand",
    "ScorePoint",
    "ScoreRange",
    "KernelCapability",
    "KernelError",
    "KernelReport",
    "KernelDiagnostic",
    "ImportReport",
    "ExportReport",
    "RecoveryReport",
    "registerSelector",
    "registerEvent",
    "snapshotId",
    "CORE_COMPILED_REGISTRATION_ENTRIES",
    "decodeKernelStartupManifest",
    "decodeCoreSelectorRequest",
    "register",
    "unregister",
    "replaceContribution",
    "sealRegistry",
    "registryVersion",
    "KernelRegistryChangedEvent",
    "TechniqueDefinitionContribution",
    "MigrationContribution",
    "CORE_MIGRATION_STEPS",
    "createOperationKernelIssue",
    "createMigrationKernelIssue",
    "createReportKernelIssue",
    "buildKernelReport",
    "decodeDiagnosticInput",
    "decodeModuleIssueSource",
    "migrateScoreDocumentWithDependencies",
    "readScoreDocumentFile",
    "writeScoreDocumentFile",
    "ImporterContribution",
    "ExporterContribution",
    "TemplateContribution",
    "OFFICIAL_MODULE_SDK_V1_LIMITS",
    "ModuleKernelErrorBase",
    "createModuleKernelIssueV1",
    "defineDomainCommandV1",
    "defineModuleEffectV1",
    "defineDomainCommandContributionV1",
    "defineDomainCommandRegistrationEntryV1",
    "compileOfficialModuleCatalogV1",
    "getKernelIntegratedCatalogState",
    "KernelErrorBase",
  ];
  forbidden.forEach((name) => assert.equal(name in coreKernel, false));

  const publicIndex = readFileSync(
    resolve(process.cwd(), "src", "core-kernel", "index.ts"),
    "utf8",
  );
  [
    "commands/catalog",
    "commands/mutations",
    "commands/runtime",
    "commands/strict-codec",
    "commands/target-resolver",
    "read/address-codec",
    "read/deep-freeze",
    "read/entity-index",
    "read/session-state",
    "read/snapshot",
    "events/facts",
    "events/runtime",
    "session/runtime",
    "errors/kernel-error",
    "reports/build-report",
    "reports/strict-codec",
    "migration/steps",
  ].forEach((internalModule) =>
    assert.equal(publicIndex.includes(internalModule), false),
  );
  [
    'export * from "./registry/builtins"',
    'export * from "./registry/runtime"',
    "registry/strict-codec",
    "CORE_COMPILED_REGISTRATION_ENTRIES",
    "buildRegistryCandidate",
    "NormalizedRegistryModule",
    "RegistryCandidateState",
    "RegistryCandidateResult",
  ].forEach((privateRegistryBoundary) =>
    assert.equal(publicIndex.includes(privateRegistryBoundary), false),
  );

  const registryContracts = readFileSync(
    resolve(process.cwd(), "src", "core-kernel", "registry", "contracts.ts"),
    "utf8",
  );
  const registryRuntime = readFileSync(
    resolve(process.cwd(), "src", "core-kernel", "registry", "runtime.ts"),
    "utf8",
  );
  for (const registrySource of [registryContracts, registryRuntime]) {
    assert.equal(
      registrySource.includes('"registry.contribution-kind-mismatch"'),
      false,
    );
  }
});
